# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    environment: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [ 18.x ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - run: npm i
      - run: npm run build

      - name: Prepare git
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git fetch

      - name: Stash changes
        run: |
          git add docs/*
          git stash save
          git stash list
          git stash show

      - name: Prepare old branch
        run: |
          git diff
          git checkout -b gh-pages
          git pull origin gh-pages
          git rm -rf docs

      - name: Unstash changes
        run: |
          git stash pop
          git add docs

      - name: Commit and push changes
        run: |
          files_changed=$(git diff --cached --numstat | wc -l)
          echo $files_changed " files changed"
          if [ $files_changed -gt 0 ]; then
            git commit -m "Automated build"
            git push https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git HEAD:gh-pages
          fi
